# site_name: HisabKitab Docs
# theme:
#   name: material
#   features:
#     - navigation.tabs
#     - navigation.sections
#     - navigation.expand
#     - navigation.indexes
#     - toc.integrate
#     - navigation.top
#     - search.suggest
#     - search.highlight
#     - content.tabs.link
#     - content.code.annotation
#     - content.code.copy
#   language: en
#   palette:
#     - media: "(prefers-color-scheme: light)"
#       scheme: default
#       primary: indigo
#       accent: deep purple
#       toggle:
#         icon: material/brightness-7
#         name: Switch to dark mode
#     - media: "(prefers-color-scheme: dark)"
#       scheme: slate
#       primary: deep purple
#       accent: indigo
#       toggle:
#         icon: material/brightness-4
#         name: Switch to light mode
#   font:
#     text: Roboto
#     code: Roboto Mono
#   favicon: assets/favicon.png
#   logo: assets/logo.png

# plugins:
#   - search

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/Baebabe
#     - icon: fontawesome/brands/linkedin
#       link: https://www.linkedin.com/in/baibhav-singh-28a809249/

# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#       line_spans: __span
#       pygments_lang_class: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - admonition
#   - pymdownx.arithmatex:
#       generic: true
#   - footnotes
#   - pymdownx.details
#   - pymdownx.superfences
#   - pymdownx.mark
#   - attr_list
#   - md_in_html
#   - pymdownx.emoji:
#       emoji_index: !!python/name:material.extensions.emoji.twemoji
#       emoji_generator: !!python/name:material.extensions.emoji.to_svg
#   - toc:
#       permalink: true

# extra_css:
#   - stylesheets/extra.css

# extra_javascript:
#   - javascripts/extra.js

site_name: HisabKitab Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: logo.png

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Baebabe
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/baibhav-singh-28a809249/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js